:configurationsdir: ./configurations

== Smarti Configuration Guide

The configuration of Smarti has two different levels


=== Client Configuration

The client configuration allows to define the configuration for specific clients.
Configuration changes are applied immediately (no restart required).
Configuration is done via the <<index.adoc#_client_configuration_web_service, client configuration web service>> or via the provided configuration UI.

include::{configurationsdir}/administration-ui.adoc[Administration user interface]


=== Application Configuration

Smarti is deployed as Spring Boot Application. It supports all configuration options as https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html[documented for Spring Boot].

The `smarti-application` module includes an `application.properties` file providing defaults. This ensures that Smarti does start correctly without any further configuration needed

To apply custom configuration:

* When using one of the installation packages for Debian or RedHat the main configuration file is located at `etc/smarti/application.properties`.
* When using the runnable JAR the `application.properties` needs to be in `./config` or directly in the working directory.

A list of well known configuration option can be found [here](TODO)

include::{configurationsdir}/application-configuration.adoc[Application configuration]

include::{configurationsdir}/analysis-components.adoc[Analysis Components]
