:resourcesdir: ../../dist/src/main/resources/
:configurationsdir: ./configurations
:commonsdir: ./commons

== Quickstart Guide: Running Rocket.Chat with integrated Smarti
This guide will enable you to get Smarti running together with Rocket.Chat.
By following this step by step tutorial you will learn:

1. How to setup Smarti
2. How to setup Rocket.Chat
3. How to integrate them

=== Smarti setup

==== Preparation

Before launching Smarti on your local system it is recommended to create a specific folder structure for libraries and configuration files on your filesystem.
The following steps explain how the directory structure is typically organized and how to create the corresponding files.
By following this section your final working-directory should look like this:

....
working-directory/
  smarti-${version}-exec.jar
  application.properties
  german-stopwords.txt
  logback.xml
  startup.sh
  ext/
    stanford-corenlp-3.6.0-models-german.jar
    stanford-corenlp-3.6.0.jar
  solrlib/
  solr-ressources/
    crawl-dbsystel.zip
    wikipedia-de.zip
....

===== 1. Create a Smarti working directory with the following subfolders:

....
working-directory/
  ext/
  solrlib/
  solr-ressources/
....

==== Build Smarti
The first step is to build smarti to get the executable jar.
When run `mvn clean install` a executable jar will be created in the directory: `smarti/application/target/smarti-${version}-exec.jar` +
Copy the `smarti-${version}-exec.jar` in your working-directory (see final working-directory example)
The resulting working-directory should look like this: +
....
working-directory/
  smarti-${version}-exec.jar
  ext/
  solrlib/
  solr-ressources/
....

==== Download Stanford NLP
Download the stanford nlp like shown in <<{commonsdir}additional-components.adoc#Enable Stanford NLP,Enable Stanford NLP>> chapter. +
Create a folder named `ext` in the working-directory and move the nlp libraries into the `ext` folder (see final working-directory example).
The resulting working-directory should look like this: +
....
working-directory/
  smarti-${version}-exec.jar
  ext/
    stanford-corenlp-3.6.0-models-german.jar
    stanford-corenlp-3.6.0.jar
  solrlib/
  solr-ressources/
....

==== Stopwords for Smarti
Stopwords are used from the stanford nlp to filter out meaningless words for the analysis for a specific language. +
Download the following german-stopwords.txt or create your own:
https://github.com/collective/collective.solr/blob/master/etc/german-stopwords.txt[german-stopwords.txt] +
Move the german-stopwords.txt to your working-directory. +
The resulting working-directory should look like this: +
....
working-directory/
  smarti-${version}-exec.jar
  german-stopwords.txt
  ext/
    stanford-corenlp-3.6.0-models-german.jar
    stanford-corenlp-3.6.0.jar
  solrlib/
  solr-ressources/
....

==== Logback for Smarti
To specify log information for smarti you can use a logback.xml. +
It is recommended to use the following logback.xml: +

[source,xml]
----
include::{resourcesdir}/logback.xml[]
----

Move the logback.xml into your smarti working-directory.
The resulting working-directory should look like this: +
....
working-directory/
  smarti-${version}-exec.jar
  german-stopwords.txt
  logback.xml
  ext/
    stanford-corenlp-3.6.0-models-german.jar
    stanford-corenlp-3.6.0.jar
  solrlib/
  solr-ressources/
....


==== Smarti example configuration
Smarti can be configured using a `application.properties`. The `application.properties` must be placed in the same directory the `smarti-${version}-exec.jar` is executed. +
All possible configurations are shown in <<{configurationsdir}application-configuration.adoc#Overview about Spring Boot Configuration, Overview about Spring Boot Configuration>> chapter. +

To get started the following `application.properties` is recommended:
----
include::{resourcesdir}/application.properties]
----


[NOTE]
====
The following paths might have to be changed to your local absolut paths: +
solrcore.wikipedia.de.resource +
solrcore.crawl.systel.resource +
====

[NOTE]
====
The admin password for Smarti is autogenerated and shown during startup of Smarti. +
To set a specific password use the following configuration: +
security.password
====

Move the application.properties xinto your smarti working-directory.
The resulting working-directory should look like this: +
....
working-directory/
  smarti-${version}-exec.jar
  german-stopwords.txt
  application.properties
  logback.xml
  ext/
    stanford-corenlp-3.6.0-models-german.jar
    stanford-corenlp-3.6.0.jar
  solrlib/
  solr-ressources/
    crawl-dbsystel.zip
    wikipedia-de.zip
....

==== Startup Script for Smarti
To start Smarti it is recommended to use a `startup.sh` script. +
It is recommended to use the following script:
....
#!/bin/bash
java -Xrunjdwp:transport=dt_socket,address=8787,server=y,suspend=n\
     -Dspring.profiles.active=local\
     -Xmx4g -jar -Xdebug smarti-${version}-exec.jar\
     --solrlib.home=solrlib
....

[NOTE]
====
In order to use the script the exact version of the smarti-${version}-exec.jar has to be specified
====

==== Remote Debugging
It is possible to debug the Smarti application remotely by using a debugging port when starting Smarti. +
The port can be specified with `address=8787` (see Startup Script for Smarti) when executing the jar file. +
In your IDE you can set up a remote debugger for Smarti and connect to the smarti host (localhost) with the specified port (8787).

To avoid debugging problems make sure the smarti${version}-exec.jar has the same version as the remotely debugged project.

=== Rocket.Chat setup

==== Update packages
Before building Rocket.Chat all dependent node packages need to be installed. +
Run `meteor npm install` to install missing dependencies.

==== Build Rocket.Chat
To run Rocket.Chat switch into the project directory and run `meteor`

==== Build Rocket.Chat for deployment
To build Rocket.Chat for deployment use the following command: +
`meteor build --server-only ${target-directory}` +
This will build Rocket.Chat and create an tar.gz file. +
Switch to the `target-directory` and extract the Rocket.Chat.tar.gz file on the deployment platform. +
Change directory to `bundle/programs/server` and run `meteor npm install` again. +
Rocket.Chat is ready to run now.

[NOTE]
====
There might accur an error related to `google-vision`. +
Switch to `npm/node_modules/meteor/rocketchat_google-vision` and run `meteor npm install grpc` in order to fix this error.
====

==== Setup environment configuration
Rocket.Chat can be configured using environment variables. +
Here are some useful variables to configure the startup of Rocket.Chat: +
.Rocket.Chat Configuration
|===
|Environment Variable |Example Value | Context

|MONGO_ URL
|mongodb://localhost:27017/rocketchat
|URL to reach external mongoDB

|MONGO_OPLOG_URL
|mongodb://localhost:27017/local
|Opolog URL for mongoDB

|TEST_MODE
|true
|Set true to run tests for Rocket.Chat
|===

In addition there are some configuration, that can be set by environment variables to configure the smarti connection.
|===
|Environment Variable |Example Value | Context

|OVERWRITE_SETTING_DBS_AI_Redlink_Domain
|clientname
|Name of the Rocket.Chat clientname

|OVERWRITE_SETTING_DBS_AI_Source
|2
|Set AI mode (2 = Smarti)

|OVERRIDE_SETTING_DBS_AI_Enabled
|true
|Activate Knowledgebase

|OVERWRITE_SETTING_DBS_AI_Redlinkl_Hook_Token
|key123
|Set Smarti token

|OVERWRITE_SETTING_DBS_AI_Redlink_URL
|http://localhost:8080/
|Set Smarti host address

|===

==== Start Rocket.Chat
Rocket.Chat gets automatically executed when run `meteor` in the project directory.
To run Rocket.Chat in a deployment area execute the following command: +
`node bundle/main.js`

==== Run Rocket.Chat Tests
To run Rocket.Chat tests the `TEST_MODE=true` has to be set, otherwise tests will fail. +
Rocket.Chat uses mocha.js for testing. To run all tests execute: `meteor npm run chimp-test`.

==== Internal Rocket.Chat configuration for Smarti
To integrate Smarti in Rocket.Chat it must be configured inside the Rocket.Chat application first.
Enter the 'Administration' settings and go to 'Assistify' under 'Configuration'and fill out the form 'Knowledge Base' as below:
