== System requirements

*Server sizing*

* [*] DualCore-CPU (> 2GHz)
* [*] 4GB RAM
* [*] 2GB temporary Storage

*Operating systems*

* [*] Debian (e.g. http://releases.ubuntu.com/16.04/[Ubuntu 16.04. LTS])
* [*] Red Hat (e.g. https://access.redhat.com/articles/3078#RHEL7[Red Hat Enterprise Linux 7])
* [*] Amazon (e.g. https://aws.amazon.com/amazon-linux-ami/2017.03-release-notes/[Amazon Linux 2017.03])

*System components*

* [*] https://java.com/[JavaVM], version 1.8 (application default port: `8080`)
* [*] https://www.mongodb.com/[MongoDB], version >= 2.6 (database default port: `27017`)

*Build components*

* [*] https://maven.apache.org/[Apache Maven] (`maven`)
* [*] http://sass-lang.com/[Sass] (`sass`)
* [*] http://compass-style.org/[Compass] (`ruby-compass`)

*Additional components*

* [*] Third-Party Dependencies
+
NOTE: For detailed information about third party libraries read section <<installation.adoc#,Third-Party Dependencies and Licenses>>.

* [*] https://github.com/stanfordnlp/CoreNLP[Stanford CoreNLP]
+
NOTE: Except the Stanford NLP libraries (GPL licensed), all direct runtime-dependencies such as third-party libraries are packaged with the main executable. Where to get and place the Stanford NLP libraries is explained in section <<developers-guide.adoc#,Enable Stanford NLP>>.

'''

*Production vs. Development*

CAUTION: *Smarti service* +
As Smarti is a https://projects.spring.io/spring-boot/[Spring Boot] application it can be started by directly launching the executable jar.
If you like to setup your development client or a non-productive server read section <<developers-guide.adoc#,Build and Run>> explains how to do start Smarti by executing the executable jar.
To run Smarti in production it is recommended to deploy the `deb` or `rpm` package on your target environment instead executing the jar directly.
Read section <<installation.adoc#,Smarti Installation Guide>> to learn more about how to deploy smarti on a server.

CAUTION: *Dedicated MongoDB* +
In a production scenario it is absolutely recommended to run MongoDB on a dedicated system.
If you like to run MongoDB on the same machine as the Smarti application `4 GB` RAM are insufficient.
A developer client should have at least `8 GB` RAM.
