==== Query Builder Configurations

`QueryBulder` are one type of components that can be configured
with the client configuration.

===== Solr Search Query Builder

The Solr Search Query Builder uses the <<analysis-components#_latch_template,LATCH Template>> to build a Solr Query based on the configured Solr Endpoint Configuration.

Solr Endpoint Configurations are Client specific and are set by using the <<Client Configuration>> and or the <<Client Configuration UI>>.

The following listing shows the JSON if such an configuration

[source,json]
----------------------
{
    "_class": "io.redlink.smarti.query.solr.SolrEndpointConfiguraion",
    "name": null,
    "displayName": "Solr Search Test",
    "type": "solrsearch",
    "enabled": true,
    "unbound": false,
    "solrEndpoint": "http://my.solr.org/test/me",
    "search": {
        "title": {
            "enabled": true,
            "field": "title@de"
        },
        "fullText": {
            "enabled": true,
            "field": "text@de"
        },
        "spatial": {
            "enabled": true,
            "locationNameField": "location",
            "latLonPointSpatialField": null,
            "rptField": null,
            "bboxField": null
        },
        "temporal": {
            "enabled": false,
            "timeRangeField": null,
            "startTimeField": null,
            "endTimeField": null
        },
        "related": {
            "enabled": false,
            "fields": []
        }
    },
    "defaults": {
    "rows": 8,
    "fields": "*,score"
    },
    "result": {
        "numOfRows": 10,
            "mappings": {
            "title": "title",
            "description": "description",
            "type": "type",
            "doctype": "doctype",
            "thumb": "thumb",
            "link": "link",
            "date": "date",
            "source": "source"
        }
    }
}
----------------------

where:

* `_class`: This property needs to refer the Java implementation of the configuration class. The value MUST BE `io.redlink.smarti.query.solr.SolrEndpointConfiguration`
*  `name` and `displayName`: Eigher or both of those are required. `name` must be a slug name (`a-z0-9_`). If only one of the two is present the other one is set accordingly. The name MUST BE unique within all solr endpoint configurations for a Client.
*  `type`: refers to the Query Builder Component. The value MUST BE `solrsearch`
*  `enabled`: allows to disable a configuration without deleting it
*  `unbound`: set by the server (read-only). If `true` the Solr Search Query Builder is not available in Smarti
*  `solrEndpoint`: The URL if the Solr Endpoint (the Solr response handler to be used for search requests)
*  `search`: Configuration on how to build Solr Queries based on Information from the LATCH Template
** `title`: Configuration for the title search. The value of Tokens with the Roles **A**lphabet or **L**ocation will be used. The title search terms will get an increased boost.
*** `enabled`: allows to enable/disable title search.
*** `field`: the title field in the Solr index
** `fullText`: full text search. The value of Tokens with the **A**lphabet roles will be used to create search terms
*** `enabled`: allows to enable/disable full text search.
*** `field`: the full text search field in the Solr index. If `null` or empty the default field (or `df` if present) will be used
** `spatial`: **L**ocation role tokens will be used for spatial search terms.
*** `enabled`: allows to enable/disable spatial search.
*** `locationNameField`: The values of spatial tokens will be used to search in this field. If `null` or empty the default field (or `df` if present) will be used.
*** `latLonPointSpatialField`: Lat/long information of Tokens will be used to create query terms for this field. Spatial Tokens without those information will be ignored.
*** `rptField`: Lat/long information of Tokens will be used to create query terms for this field. Spatial Tokens without those information will be ignored.
*** `bboxField`: Lat/long information of Tokens will be used to create query terms for this field. Spatial Tokens without those information will be ignored.
** temporal: Tokens with the role **T**ime will be considered for temporal searches.
*** `enabled`: allows to enable/disable temporal search.
*** `timeRangeField`: Supports temporal queries on a Solr field using the `DateRangeField` field type
*** `startTimeField`: Supports temporal queries on a Solr field using the date field type
*** `endTimeField`: Optional time range support for Solr schemas that use a start/end date field for storing ranges
** `related`: Allows to generate Solr MLT queries to suggest similar documents. This will use the content of the Conversation to search for similar content. Typically this should be only enabled if all other options are disabled.
*** `enabled`: allows to enable/disable Solr MLT queries.
*** `fields`: Array with the fields used for Solr MLT
* `defaults`: A map with solr parameters that are sent with every request (examples `"fq" : "source:(news archive)"` or `"df": "text_de"`, `"fields": "*,score"`, `"rows": 10`, ...)
* `result`: Defines how results are processed
** `numOfRows`: defines the nuber of results in the UI
** `mappings`: Defines how Solr document fields in the results are mapped to fields known by the UI presenting results
*** `title`: the title as shown in the UI
*** `description`: the description as shown in the UI
*** `type`: the type of the result
*** `doctype`: the document type of the result (e.g. `text/html`)
*** `thumb`: the thumbnail used in the UI
*** `link`: the link to the result
*** `date`: the date for the result (e.g. the modification date)
*** `source`: the source of the result

NOTE: The defaults can be set in via `application.properties`. See <<Query Builder Defalt Configuration>> for details.

==== Conversation Search Query Builder

A `Conversation Search Query Builder` offers relevant conversations that took place earlier covering a similar or related
topic.
There are two different approaches how _relevant_ is defined:

* _Keyword-Based Similarity_ determines similar conversations based on detected keywords.
* _Content-Based Similarity_ uses `more-like-this`-similarity on the initial message of other conversations.

The following configuration options are available for `Conversation Search Query Builder`s:

[source,json]
----------------------
{
  "pageSize": 3,
  "filter": [
  	"support_area"
  ]
}
----------------------

where:

* `pageSize`: the default number of related conversations.
* `filter`: fields from `metadata` that should be used for filtering (Solr `fq`-parameter)