== Smarti Changelog

This document shows the changes that are introduced into Smarti with the releases.

=== Smarti 0.5.0 Release Notes
07 August, 2017

Smarti 0.5.0 is a technical architecture release. For now basic decisions about the fundamental software design are not complete.
In short this version of Smarti solves some security aspects, ensures backward compatibility to version 0.3.0 and fixes some bugs.
Next to a https://assistify.github.io/smarti/[new comprehensive development documentation] Smarti 0.5.0 introduces lifecycle management for stored conversations.

==== New in Smarti 0.5.0
This release introduces an API that allows to manage the lifecycle of stored conversation, including:

* JSON-based im- and export of conversations,
* mark conversations obsolete by setting an expiration date,
* authors may now edit their conversation's texts or remove messages

==== Improved in Smarti 0.5.0
* https://github.com/redlink-gmbh/smarti/issues/32[#32 - Added an API for conversational lifecycle management]
* https://github.com/redlink-gmbh/smarti/issues/32[#33 - Added an UI for conversational lifecycle management]
* https://github.com/redlink-gmbh/smarti/issues/32[#37 - Added support for JSON-based conversation im- and export]
* https://github.com/redlink-gmbh/smarti/issues/32[#55 - Added a complete documentation for the `application.properties`]
* https://github.com/redlink-gmbh/smarti/issues/32[#12 - Added support for integrated Swagger UI in order to access REST API documentation]
* https://github.com/redlink-gmbh/smarti/issues/32[#56 - Improved the client model in order to implement the authentication concept]
* https://github.com/redlink-gmbh/smarti/issues/32[#31 - Fixed issue where greetings like 'Hi' have been extracted as keywords]
* https://github.com/redlink-gmbh/smarti/issues/32[#46 - Fixed issue where clients have been allowed to access conversations of other clients]
* https://github.com/redlink-gmbh/smarti/issues/32[#53 - Fixed issue where queries have to be recalculate if the client configuration has changed]

==== Upgrading
With `0.5.0`, the datamodel has changed so data from older installations
must be migrated to the new model.

A migration script is available and must be applied manually:
[source,javascript]
------------------------------------------------
var conversation = 'conversations',
    configuration = 'configuration',
    client = 'client';

// create all clients
db.getCollection(conversation).aggregate([
    { $project: { _id: '$context.domain' } },
    { $group: { _id: '$_id'}},
    { $project: {
        _id: { $literal: new ObjectId() },
        name: '$_id',
        lastUpdate: { $literal: ISODate() },
        defaultClient: { $literal: false }
    } },
    { $out: client}
]);
db.getCollection(client).find().forEach(function(c) {
    db.getCollection(conversation).update(
        { 'context.domain': c.name },
        { $set: { owner: c._id }},
        { multi: true }
    );
    db.getCollection(configuration).update(
        { client: c._id },
        { $setOnInsert: {
            created: new ISODate(),
            modified: new ISODate(),
            config: {
                "queryBuilder" : [
                    {
                        "name" : "conversationmlt",
                        "displayName" : "Related Conversations",
                        "type" : "conversationmlt",
                        "enabled" : true,
                        "unbound" : false,
                        "configuration" : {

                        }
                    },
                    {
                        "solrEndpoint" : "http://host.domain.org:8983/solr/change-me",
                        "search" : {
                            "title" : {
                                "enabled" : false,
                                "field" : ""
                            },
                            "fullText" : {
                                "enabled" : true,
                                "field" : ""
                            },
                            "spatial" : {
                                "enabled" : true,
                                "locationNameField" : ""
                            },
                            "temporal" : {
                                "enabled" : false
                            },
                            "related" : {
                                "enabled" : false,
                                "fields" : [ ]
                            }
                        },
                        "defaults" : {
                            "rows" : 10,
                            "fields" : "*,score"
                        },
                        "result" : {
                            "numOfRows": 10,
                            "mappings" : {
                                "title": "title",
                                "description": "description",
                                "type": "type",
                                "doctype": "doctype",
                                "thumb": "thumb",
                                "link": "link",
                                "date": "date",
                                "source": "source"
                            },
                        },
                        "name" : "search-endpoint-0",
                        "displayName" : "Search Endpoint",
                        "type" : "solrsearch",
                        "enabled" : false,
                        "unbound" : false,
                        "configuration" : {

                        },
                        "_class" : "io.redlink.smarti.query.solr.SolrEndpointConfiguration"
                    },
                    {
                        "name" : "conversationsearch",
                        "displayName" : "conversationsearch",
                        "type" : "conversationsearch",
                        "enabled" : true,
                        "unbound" : false,
                        "configuration" : {

                        }
                    }
                ]
            }
        }},
        { upsert: true }
    );
});
------------------------------------------------

=== 0.4.0 (TBD)
==== Bug fixes
==== Improvements and Refactoring
==== Build and Distribution

=== Pre 0.4.0
For information about older releases check the https://github.com/redlink-gmbh/smarti/commits/master[history on GitHub].
