== Smarti Guide Overview

[abstract]
This is the short version of the whole documentation.
It hast external links only.
Can be used as standalone doc.

=== <<comprehensive-guide.adoc#_smarti_installation_guide,How to install>>

Installation packages are provided for https://www.debian.org[Debian]- and https://www.redhat.com[RedHat]-based systems. Alternatively the application can
be started by directly launching the executable jar.

```bash
$ java -jar smarti-${smarti-version}-exec.jar
```

Check out a detailed <<comprehensive-guide.adoc#_smarti_installation_guide,Smarti Installation Guide>> including <<comprehensive-guide.adoc#_system_requirements,system requirements>>.


=== <<comprehensive-guide.adoc#_smarti_configuration_guide,How to configure>>

Smarti is configurable using either <<comprehensive-guide.adoc#_client_configuration_api,the client API>> or the <<comprehensive-guide.adoc#_client_configuration_ui,configuration UI>>, which can be found on the `{HOST}/index.html` page of the the running application.


=== <<comprehensive-guide.adoc#_smarti_integration_guide,How to integrate>>

Through Smarti's conversational RESTful-API it can be seamlessly integrated into any Chat-based communication platform.
To learn how ti integrate Smarti into chat applications read <<comprehensive-guide.adoc#_conversational_api,Conversational API>>.

For now Smarti is working with https://rocket.chat[Rocket.Chat] conversations, where it can be smoothly integrated via a https://github.com/assistify/Rocket.Chat[RC plugin].
Lookup the <<comprehensive-guide.adoc#_rocket_chat_plugin,Rocket.Chat plugin description>> for further information.


=== <<comprehensive-guide.adoc#_smarti_troubleshooting_guide,How to troubleshoot>>

In some cases, Smarti will not do what you expect it to do. Maybe you have encountered an issue that is already known.
Find solved solutions and known issues in our <<comprehensive-guide.adoc#_smarti_troubleshooting_guide,Smarti Troubleshooting Guide>>.


=== <<comprehensive-guide.adoc#_smarti_developer_guide,How to develop>>

*Smarti* is a https://java.com/[Java]-Application based on the https://spring.io/[Spring Framework].
The application uses https://www.mongodb.com/[MongoDB] as database and http://lucene.apache.org/solr/[Apache Solr] as search engine.
After checking out the sources from https://github.com/redlink-gmbh/smarti/[GitHub] and installing the build components (`ruby`, `ruby-sass`, `ruby-compass`) a build can be executed as simple

```bash
$ mvn clean install [ -Pdeb | -Prpm ]
```
Read the <<comprehensive-guide.adoc#_smarti_developer_guide,Developers Guide>> to become a Smarti developer.

=== <<comprehensive-guide.adoc#_smarti_contribution_guide,How to contribute>>

Smarti is an Open Source project so everyone is encouraged to improve it. Don't hesitate to report bugs, provide fixes or
share new ideas with us. Use the issue tracker or send a pull request. To learn more about contributing and how to become a Smarti commiter, read the <<comprehensive-guide.adoc#_smarti_contribution_guide,Smarti Contribution Guide>>.
